variables:
  dockerId: davidhayes  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: prometheus  # Replace with the name of the image you want to publish
jobs:
  - job: 'BuildDockerImage'
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'davidhayes/prometheus'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'nanoserver$(NanoServerVersion)'
          arguments: 'nanoServerVersion=$(NanoServerVersion) prometheusVersion=$(PrometheusVersion)'