jobs:
  - job: 'BuildDockerImage'
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'davidhayes/prometheus'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: |
            nanoserver$(NanoServerVersion)prometheus$(PrometheusVersion)
          arguments: '--build-arg nanoServerVersion=$(NanoServerVersion) --build-arg prometheusVersion=$(PrometheusVersion)'
